																			document.write("</td>");
																		document.write("</tr>");
																	document.write("</table>");
																document.write("</td>");
															document.write("</tr>");
														document.write("</table>");
													document.write("</td>");
													document.write("<td valign='top'>");
														document.write("<table cellpadding='0' cellspacing='0' border='0' width='2' height='100%'>");
															document.write("<tr>");
																document.write("<td>");
																	document.write("<div style='height:2px; width:2px;'><spacer></spacer></div>");
																document.write("</td>");
															document.write("</tr>");
															document.write("<tr height='100%' bgcolor='#000000'>");
																document.write("<td></td>");
															document.write("</tr>");
														document.write("</table>");
													document.write("</td>");
document.write("</tr>");
document.write("<tr>");
													document.write("<td>");
														document.write("<div style='height:2px; width:2px;'><spacer></spacer></div>");
													document.write("</td>");
													document.write("<td bgcolor='#000000' width='100%'></td>");
													document.write("<td bgcolor='#000000'></td>");
												document.write("</tr>");
											document.write("</table>");
										document.write("</td>");
									document.write("</tr>");
								document.write("</table>");
							document.write("</td>");
						document.write("</tr>");
						document.write("<tr height='1'>");
							document.write("<td bgcolor='#cccccc'></td>");
						document.write("</tr>");
						document.write("<tr height='100'>");
							document.write("<td class='copy' style='background:#ffffff url(images/copy_bgrpt.gif) top left repeat-x; border-top:1px solid #ffffff;'>David Shapiro</td>");
						document.write("</tr>");
					document.write("</table>");
				document.write("</td>");
			document.write("</tr>");
		document.write("</table>");
		document.write("<div style='display: none'><b></b><b></b><i></i><b></b><i></i><b></b><b></b><b></b><i></i><b></b><i></i><i></i><i></i><i></i><i></i><i></i></div>");
