		document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='100%' background='images/main_bg.gif'>");
			document.write("<tr>");
				document.write("<td>");
					document.write("<table cellpadding='0' cellspacing='0' border='0' width='780' height='100%'>");
						document.write("<tr height='279'>");
							document.write("<td style='&#10;&#9;&#9;background:#f5f5f5 url(images/top.jpg) top left no-repeat; border-bottom:1px solid #ffffff;&#10;&#9;'>");
								document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='278'>");
									document.write("<tr height='100%'>");
										document.write("<td align='right' style='padding:0px 50px 10px 0px;'>");
											document.write("<table cellpadding='0' cellspacing='0' border='0'>");
												document.write("<tr>");
													document.write("<td align='center'>");
														document.write("<img src='images/logo.gif' border='0' alt=''><br>");
														document.write("<div class='mycompany'>David Shapiro</div>");
														document.write("<div align='left' class='slogan'>Speed, Relibility and Quality</div>");
													document.write("</td>");
												document.write("</tr>");
											document.write("</table>");
										document.write("</td>");
									document.write("</tr>");
									document.write("<tr height='26'>");
										document.write("<td style='padding-right:15px;' align='right'>");
